name: amqp_rpc_binder
version: 0.1.0
description: >
  amqp_rpc_binder allow to create remote procedure call to a distant ressources through rabbitMQ
author: ProfileRH, PLATEL Kevin <platel.kevin@gmail.com>
homepage: https://github.com/ProfileRH/amqp_rpc_binder
environment:
  sdk: ">=1.15.0 <2.0.0"
dependencies:
  rpc: ">=0.5.6 <0.6.0"
  dart_amqp: "^0.0.1"
  uuid: "^0.5.0"